version: "3.3"

services:
  app:
    build: .
    container_name: minio_webhook_discord
    command: ["pnpm", "start"]
    env_file: .env
    environment: 
      - DOCKER=true
    ports:
      - "3000:3000"
    restart: unless-stopped
